from pathlib import Path
VISTRO_HOME = Path.home() / "vistro"
VISTRO_ROOT = VISTRO_HOME / "root"
VISTRO_USERS = VISTRO_ROOT / "users"
VISTRO_PROGRAMS = VISTRO_ROOT / "programs"
VISTRO_DATA = VISTRO_ROOT / "data"
VISTRO_SHELL = VISTRO_ROOT / "shell"
APP_COMMAND_FILE = "command.AppCommand"
APP_MANIFEST_FILE = "manifest.json"
APP_INSTALLER_EXT = ".AppInstaller"
SHELL_EXT = ".shell"
SHELL_MANIFEST = "manifest.json"
SHELL_BIN = "bin"
SHELL_MAIN = "Main"
PROFILE_FILE = "profile.json"
SENSITIVE_DIRS = [
    VISTRO_ROOT,
    VISTRO_USERS,
    VISTRO_PROGRAMS,
    VISTRO_DATA,
    VISTRO_SHELL,
]
SENSITIVE_FILES = [PROFILE_FILE]
ADMIN_USER = "admin"
API_HOST = "127.0.0.1"
API_PORT = 7070
VISTRO_OS_NAME = "Vistro x86_64"
VISTRO_VERSION = "0.1.0"
MACHINE_LANG_MAGIC = "0x"
MACHINE_LANG_EXT = ".AppCommand"
HASH_ALGORITHM = "sha256"
TOKEN_LENGTH = 32
TOKEN_EXPIRY_SECONDS = 3600
SANDBOX_ROOT = VISTRO_ROOT
